<?php
/**
 * Auto generated by PRADO - WSAT on 2018-02-02 08:31:03.
 * @author 
 */
class LBsLog extends TActiveRecord
{
	const TABLE='bs_log';

	public $log_id;
	public $level;
	public $category;
	public $logtime;
	public $message;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->category;
	}
}