<?php
/**
 * Auto generated by PRADO - WSAT on 2018-02-22 10:33:18.
 * @author 
 */
class LBsUsuarios extends TActiveRecord
{
	const TABLE='bs_usuarios';

	public $id_usuarios;
	public $foto;
	public $nombre;
	public $id_dependencia;
	public $dependencia;
	public $cargo;
	public $user;
	public $pass;
	public $correo;
	public $telefono;
	public $direccion;
	public $observaciones;
	public $id_roles;
	public $activo;
	public $borrado;
	public $permisos;
	public $cadena_referencia;
	public $fecha_alta;
	public $fecha_actualizado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_roles' => array(self::BELONGS_TO, 'LBsRoles', 'id_roles'),
		'bs_usuarios_activos' => array(self::HAS_MANY, 'LBsUsuariosActivos', 'id_usuarios'),
		'ms_incidencias' => array(self::HAS_MANY, 'LMsIncidencias', 'id_usuarios')
	);

	public function __toString() {
		return $this->foto;
	}
}